version: "3"

services:

  libretranslate:
    image: libretranslate/libretranslate
    container_name: libretranslate
    ports:
      - "127.0.0.1:2012:5000"
    environment:
      - LT_CHAR_LIMIT=10000
      - LT_REQ_LIMIT=30
      - LT_BATCH_LIMIT=2
      - LT_SSL=True
      - LT_FRONTEND_LANGUAGE_SOURCE=en
      - LT_FRONTEND_LANGUAGE_TARGET=fr
      - LT_API_KEYS=True
    volumes:
      - /docker/libretranslate/api_keys.db:/app/api_keys.db
      - /docker/libretranslate/suggestions.db:/app/suggestions.db
    restart: unless-stopped