channel_threads: 4
feed_threads: 4

db:
  user: kemal
  password: kemal
  host: localhost
  port: 5432
  dbname: invidious

full_refresh: false
https_only: true
domain: invidious.pussthecat.org
external_port: 443

# disable user registration
registration_enabled: false
login_enabled: false

# disable the "popular" list
popular_enabled: false

default_user_preferences:
  # enable proxy mode
  local: true
  # dash by default to enable 1080p
  quality: dash
  # set dash quality to use the best possible quality by default
  quality_dash: best
  # disable the video suggestion
  related_videos: false
  # set the default home to a search engine layout page
  default_home: "Search"
  # disable the trending / popular pages
  feed_menu: []
  # only allow the youtube comments
  comments: ["youtube",""]
  # dark theme everything
  dark_mode: true
