channel_threads: 2
feed_threads: 1
db:
  user: kemal
  password: kemal
  host: localhost
  port: 5432
  dbname: invidious
full_refresh: false
https_only: true
domain: invidious.pussthecat.org

# disable user registration
registration_enabled: false
login_enabled: false

# disable the "top", showing most watched videos on this instance
top_enabled: false


default_user_preferences:
  # enable proxy mode
  local: true
  # dash by default to enable 1080p
  quality: dash
  # disable the video suggestion
  related_videos: false
  # disable the trending / popular / top page
  feed_menu: []
  # only allow the youtube comments 
  comments: ["youtube",""]
  # your eyes will like it
  dark_mode: true
