services:

  peertube:
    container_name: peertube
    image: docker.io/chocobozzz/peertube:v[VERSION]-bullseye
    restart: "no"
    ports:
      - "127.0.0.1:2016:9000"
    env_file:
      - .env
    volumes:
      - "peertube-assets:/app/client/dist"
      - "/[REDACTED]/PeerTube:/data" # Video storage isn't on the system drive
      - "/docker/peertube/config:/config"
    depends_on:
      - peertube-postgres
      - peertube-redis

  peertube-postgres:
    container_name: peertube-postgres
    image: docker.io/postgres:[VERSION]-alpine
    restart: "no"
    env_file:
      - .env
    volumes:
      - "/docker/peertube/db:/var/lib/postgresql/data"

  peertube-redis:
    container_name: peertube-redis
    image: docker.io/redis:[VERSION]-alpine
    restart: "no"
    volumes:
      - "/docker/peertube/redis:/data"

volumes:
  peertube-assets:
