services:

  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:2004:8080"
    volumes:
      - "/docker/searxng/settings.yml:/etc/searxng/settings.yml"
    network_mode: bridge # https://stackoverflow.com/a/57152380
