services:

  teddit:
    container_name: teddit
    image: docker.io/teddit/teddit:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:9999:8080"
    environment:
      - "DOMAIN=teddit.pussthecat.org"
      - "THEME=dark"
      - "USE_HELMET=true"
      - "USE_HELMET_HSTS=true"
      - "TRUST_PROXY=true"
      - "NSFW_ENABLED=false"
      - "POST_COMMENTS_SORT=top"
      - "CACHE_CONTROL=true"
      - "CACHE_MAX_SIZE=10000"
      - "REDIS_HOST=teddit-redis"
      - "CLEAN_HOMEPAGE=true"
    healthcheck:
      test: ["CMD", "wget" ,"--no-verbose", "--tries=1", "--spider", "http://localhost:8080/about"]
      interval: 1m
      timeout: 3s
    depends_on:
      - teddit-redis

  teddit-redis:
    container_name: teddit-redis
    image: docker.io/redis:6.[VERSION]-alpine
    restart: unless-stopped
    environment:
      - "REDIS_REPLICATION_MODE=master"
