services:

  scribe:
    container_name: scribe
    image: registry.gitlab.com/lomanic/scribe-binaries:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:2013:8088"
    environment:
      - "LUCKY_ENV=production"
      - "PORT=8088"
      - "APP_DOMAIN=scribe.pussthecat.org"
      - "SECRET_KEY_BASE=[REDACTED]"
    network_mode: bridge # https://stackoverflow.com/a/57152380
